
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { BuildingConfig, BuildingType, TechNode } from './types';

// Map Settings
export const MAP_SIZES = {
  Small: 12,
  Medium: 20,
  Large: 32,
};

// Game Settings
export const TICK_RATE_MS = 2000; 
export const INITIAL_MONEY = 50000; // Increased for sandbox mode

// Base consumption/production rates per tick
export const POP_O2_CONSUMPTION = 0.05; // % per person
export const POP_CO2_PRODUCTION = 2;    // ppm per person
export const POP_FOOD_CONSUMPTION = 1;  // unit per person

export const BUILDINGS: Record<BuildingType, BuildingConfig> = {
  [BuildingType.None]: {
    type: BuildingType.None,
    cost: 0,
    name: 'Regolith',
    description: 'Clear area',
    color: '#ef4444',
    popGen: 0,
    incomeGen: 0,
    powerGen: 0,
    scienceGen: 0,
    oxygenGen: 0,
    co2Gen: 0,
    foodGen: 0,
    width: 1,
    height: 1,
  },
  [BuildingType.Road]: {
    type: BuildingType.Road,
    cost: 25,
    name: 'Transport Tube',
    description: 'Pressurized transit.',
    color: '#475569', 
    popGen: 0,
    incomeGen: 0,
    powerGen: 0,
    scienceGen: 0,
    oxygenGen: 0,
    co2Gen: 0,
    foodGen: 0,
    width: 1,
    height: 1,
  },
  [BuildingType.GreenRoad]: {
    type: BuildingType.GreenRoad,
    cost: 75,
    name: 'Canal Transitway',
    description: 'Algae canals & walkways.',
    color: '#0ea5e9',
    popGen: 0,
    incomeGen: 0,
    powerGen: 0,
    scienceGen: 0,
    oxygenGen: 0.2, // Algae helps
    co2Gen: -5,     // Scrubs CO2
    foodGen: 0,
    width: 1,
    height: 1,
  },
  [BuildingType.SolarPanel]: {
    type: BuildingType.SolarPanel,
    cost: 150,
    name: 'Solar Array',
    description: 'Basic power generation.',
    color: '#3b82f6',
    popGen: 0,
    incomeGen: 0,
    powerGen: 25,
    scienceGen: 0,
    oxygenGen: 0,
    co2Gen: 0,
    foodGen: 0,
    width: 1,
    height: 1,
  },
  [BuildingType.Residential]: {
    type: BuildingType.Residential,
    cost: 200,
    name: 'Habitation Stack',
    description: 'High-density living.',
    color: '#e2e8f0',
    popGen: 12,
    incomeGen: -2,
    powerGen: -4,
    scienceGen: 0,
    oxygenGen: 0,
    co2Gen: 10, // Waste processing
    foodGen: 0,
    width: 1,
    height: 1,
  },
  [BuildingType.ResearchLab]: {
    type: BuildingType.ResearchLab,
    cost: 600,
    name: 'Research Lab',
    description: 'Generates Science.',
    color: '#8b5cf6',
    popGen: 2,
    incomeGen: -10,
    powerGen: -12,
    scienceGen: 8,
    oxygenGen: -0.5,
    co2Gen: 20,
    foodGen: 0,
    width: 1,
    height: 1,
  },
  [BuildingType.Commercial]: {
    type: BuildingType.Commercial,
    cost: 450,
    name: 'Data Nexus',
    description: 'Off-world server farm.',
    color: '#3b82f6',
    popGen: 0,
    incomeGen: 25,
    powerGen: -10,
    scienceGen: 1,
    oxygenGen: -1,
    co2Gen: 30,
    foodGen: 0,
    width: 1,
    height: 1,
  },
  [BuildingType.Agriculture]: {
    type: BuildingType.Agriculture,
    cost: 350,
    name: 'Hydroponics Bay',
    description: 'Vertical farms.',
    color: '#84cc16',
    popGen: 4,
    incomeGen: 10,
    powerGen: -8,
    scienceGen: 0,
    oxygenGen: 2.5,
    co2Gen: -80,
    foodGen: 50,
    width: 1,
    height: 1,
  },
  [BuildingType.Industrial]: {
    type: BuildingType.Industrial,
    cost: 1200,
    name: 'He3 Deep Mine',
    description: 'Extracts fusion fuel.',
    color: '#f59e0b',
    popGen: 0,
    incomeGen: 85,
    powerGen: -35,
    scienceGen: 0,
    oxygenGen: -3,
    co2Gen: 150,
    foodGen: 0,
    width: 2,
    height: 2,
  },
  [BuildingType.FusionReactor]: {
    type: BuildingType.FusionReactor,
    cost: 2500,
    name: 'Fusion Reactor',
    description: 'Massive clean energy.',
    color: '#f43f5e',
    popGen: 0,
    incomeGen: -50,
    powerGen: 250,
    scienceGen: 5,
    oxygenGen: 0,
    co2Gen: 10,
    foodGen: 0,
    width: 2,
    height: 2,
  },
  [BuildingType.Park]: {
    type: BuildingType.Park,
    cost: 800,
    name: 'Exo-Biome',
    description: 'Terraformed dome.',
    color: '#10b981',
    popGen: 5,
    incomeGen: 5,
    powerGen: -15,
    scienceGen: 2,
    oxygenGen: 5.0,
    co2Gen: -150,
    foodGen: 10, // Small amount from permaculture
    width: 2,
    height: 2,
  },
};

export const TECH_TREE: TechNode[] = [
  {
    id: 'tech_basics',
    name: 'Lunar Basics',
    description: 'Standard issue colony blueprints.',
    cost: 0,
    unlocks: [BuildingType.Road, BuildingType.SolarPanel, BuildingType.Residential],
    prerequisites: [],
  },
  {
    id: 'tech_research',
    name: 'Xeno-Research',
    description: 'Unlocks scientific facilities.',
    cost: 50,
    unlocks: [BuildingType.ResearchLab],
    prerequisites: ['tech_basics'],
  },
  {
    id: 'tech_hydroponics',
    name: 'Bio-Regen Life Support',
    description: 'Farming and air recycling canals.',
    cost: 100,
    unlocks: [BuildingType.Agriculture, BuildingType.GreenRoad],
    prerequisites: ['tech_basics'],
  },
  {
    id: 'tech_commerce',
    name: 'Off-World Trade',
    description: 'Commercial hubs and data centers.',
    cost: 200,
    unlocks: [BuildingType.Commercial],
    prerequisites: ['tech_research'],
  },
  {
    id: 'tech_industry',
    name: 'Heavy Industry',
    description: 'Helium-3 extraction technology.',
    cost: 450,
    unlocks: [BuildingType.Industrial],
    prerequisites: ['tech_commerce'],
  },
  {
    id: 'tech_terraforming',
    name: 'Terraforming',
    description: 'Large scale habitability domes.',
    cost: 800,
    unlocks: [BuildingType.Park],
    prerequisites: ['tech_hydroponics'],
  },
  {
    id: 'tech_fusion',
    name: 'Nuclear Fusion',
    description: 'Unlimited power generation.',
    cost: 1500,
    unlocks: [BuildingType.FusionReactor],
    prerequisites: ['tech_industry'],
  },
];

export const INITIAL_UNLOCKED_TECHS = [
  'tech_basics',
  'tech_research',
  'tech_hydroponics',
  'tech_commerce',
  'tech_industry',
  'tech_terraforming',
  'tech_fusion'
];
